### ISSUE TITLE
It only supports methods

### ISSUE THREAD

**Issue by fregante** [sindresorhus/magic-iterable#4]
# Example

```js
const magicIterable = require('magic-iterable');

const magicElements = magicIterable(document.querySelectorAll('a'));
console.log(magicElements.textContent);
console.log(magicElements.classList.add('x'));
```

# Expected

```js
[ 'Home', 'Contacts', 'Click Here', 'Close' ]
[ undefined, undefined, undefined, undefined ]
```

# Currently

```js
function // this is the function you return at line 10
Uncaught TypeError: magicElements.classList.add is not a function
```

**Comment by sindresorhus** [comment]
I didn't think of that use-case, but should definitely be supported.

**Comment by fregante** [comment]
I'm not sure if this is possible, actually. I'm not completely familiar with Proxy, but for this to happen:

```js
Array.isArray(magicElements) === true
Array.isArray(magicElements.textContent) === true
Array.isArray(magicElements.querySelector) === true 🤔
typeof magicElements.querySelector === 'function' 🤔
```

Can something be both a function and a (real) array? Perhaps it doesn't need to be an actual array though, just an iterable (since it's called `magic-iterable` after all)

Maybe `magic-iterable` has to:

- test for `elements[0].querySelector === function`
  - if positive, return a `function` that is also iterable
  - if negative, return a plain array (basically `elements.map(el => el.textContent)`)

**Comment by fregante** [comment]
Also, to support `magicElements.classList.add`, it'd have to wrap all the mapped results in a new `magicIterable`, which means that the above is actually:

> if positive, return a `function` that is also a **`magicIterable`**

> if negative, return a plain array (basically **`magicIterable(elements.map(el => el.textContent))`**)
